config/routes.rb
Hackaton::Application.routes.draw do
  resources :posts do
    collection do
      get :select
    end
  end

  resources :services, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :pets do
    resources :posts, only: [ :new, :create ]
  end

  devise_for :users

  resource :dashboard

  root controller: :dashboards, action: :show
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_many :posts

  CAT  = 'cat'
  DOG  = 'dog'
  BIRD = 'bird'
  RABBIT = 'rabbit'

  mount_uploader :photo, ImageUploader
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show]

  # GET /pets
  # GET /pets.json
  def index
    @user = current_user
    @pets = @user.pets
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = Pet.find params[:id]
    respond_to do |format|
      format.html
      format.png  { render :qrcode => pet_url, size: 5 }
    end
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Tu mascota se ha creado con éxito.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Tu mascota se ha actualizado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = current_user.pets.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :race, :birth, :weight, :habits, :kind, :photo)
    end
end

app/views/pets/_form.html.erb
<div class='row' >
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3"> 
<%= form_for @pet, html: {multipart: true} do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="center">
      <%= image_tag @pet.photo.to_s, style: "max-width: 150px", class: 'frame-img' %>
    <div class="field">
      <%= f.label :Foto %>
      <%= f.file_field :photo %>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label">Nombre: </label>
      <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class="form-group">
    <label class="control-label">Animal: </label>
      <%= select_tag "pet[kind]", pet_kinds_for_select, class:'form-control' %>
  </div>

  <div class="form-group">
    <label class="control-label">Raza: </label>
    <%= f.text_field :race, class:'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label">Peso: </label>
    <%= f.text_field :weight, class:'form-control' %>
  </div>

  <div class="form-group">
    <label class="control-label">Fecha de nacimiento: </label>
    <%= f.date_field :birth, class:'form-control' %>
  </div>

  <div class="form-group">
    <label class="control-label">H&aacute;bitos: </label>
    <%= f.text_area :habits, class:'form-control' %>
  </div>
  <div class="center">
    <button type="submit" class="pet-button">
      <%= image_tag("check-72px.png", :alt => "Enviar") %>
    </button>
   </div> 
<% end %>
</div>
</div>

app/views/pets/edit.html.erb
<h2>EDITAR MASCOTA</h2>
<div class='divisor'></div>

<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Mis Mascotas</h1>

<div class="divisor">
  <%= image_tag("ico-perfil48px.png", alt: "Perfil") %>
</div>

<div class="row pets-grid">
  <% if @pets.blank? %>
    <div class="no-content">
      Aún no tienes mascotas. Agrega una presionando el icono +
    </div>
  <% end %>
  <% @pets.each do |pet| %>
    <div class="col-xs-6 col-sm-4 col-md-3 polaroid">
      <%= link_to pet_path(pet), { style: "background-image: url('#{image_path pet.photo}');" } do %>
        <span class="image-caption"><%= pet.name %></span>
      <% end %>
    </div>
  <% end %>
</div>

<div class="add-button">
  <%= link_to (image_tag("plus-72px.png", :alt => "Mi mascota")), new_pet_path %>
</div>

app/views/pets/new.html.erb
<h2>AGREGAR MASCOTA</h2>
<div class='divisor'></div>

<%= render 'form' %>

app/views/pets/show.html.erb
<h2>VER MASCOTA</h2>
<div class='divisor'></div>
<div class="media">
  <div class="pull-left">
     <%= image_tag @pet.photo.to_s, style: "max-width: 150px", class: 'frame-img' %>
  </div>
  <div class="media-body">
    <h3 class="media-heading"><%= @pet.name %></h3>
    <p>Raza: <%= @pet.race %></p>
    <p>Peso: <%= @pet.weight %></p>
    <p>Fecha de Nacimiento: <%= @pet.birth %></p>
  </div>
</div>
<% if (current_user == @pet.user) %>
  <%= link_to pet_path(@pet, format: :png), target: "_blank", class: "has-tooltip qr-link", 
      data: { toggle: "tooltip", placement: "bottom" }, title: "Generalo e imprimelo en la placa de tu mascota. En caso de
      extravío podrán contactarte" do %>
    <span class="qr-link-caption">Generar código QR</span>
  <% end %>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">H&aacute;bitos</div>
  <div class="panel-body">
    <p><%= @pet.habits %></p>
  </div>
</div>
<% if (current_user == @pet.user) %>
<div class="add-button">
  <%= link_to (image_tag("edit-72px.png", :alt => "Editar")), edit_pet_path(@pet) %>
</div>
<% end %>