config/routes.rb
Hackaton::Application.routes.draw do
  resources :posts do
    collection do
      get :select
    end
  end

  resources :services, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :pets do
    resources :posts, only: [ :new, :create ]
  end

  devise_for :users

  resource :dashboard

  root controller: :dashboards, action: :show
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/views/dashboards/show.html.erb
<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= link_to posts_path(k: Post::ADOPTION) do %>
      <div class="center">
        <%= image_tag("ico-adoptar96px.png", :alt => "adopta") %>  
        <h3>Adopci&oacute;n</h3>
      </div>
    <% end %>  
  </div>
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= link_to posts_path(k: Post::LOST) do %>
      <div class="center">
        <%= image_tag("ico-extraviado96px.png", :alt => "extraviados") %>  
        <h3>Extraviadas</h3>
      </div>
    <% end %>  
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
   <%= link_to posts_path(k: Post::MATE) do %>
      <div class="center">
        <%= image_tag("ico-pareja96px.png", :alt => "pareja") %>  
        <h3>Buscando Pareja</h3>
      </div> 
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= link_to services_path do %>
      <div class="center">
        <%= image_tag("ico-plus-blue96px.png", :alt => "servicios") %>  
        <h3>Servicios</h3>
      </div>
    <% end %>  
  </div>
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <%= link_to pets_path do %>
      <div class="center">
        <%= image_tag("ico-perfil96px.png", :alt => "perfil") %>  
        <h3>Perfil</h3>
      </div>
    <% end %>  
  </div>
</div>