config/routes.rb
Hackaton::Application.routes.draw do
  resources :posts do
    collection do
      get :select
    end
  end

  resources :services, only: [:index, :show]

  resources :categories, only: [:index, :show]

  resources :pets do
    resources :posts, only: [ :new, :create ]
  end

  devise_for :users

  resource :dashboard

  root controller: :dashboards, action: :show
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :pet
  belongs_to :user

  LOST     = 'lost'
  FOUND    = 'found'
  ADOPTION = 'adoption'
  MATE     = 'mate'

  scope :lost,       -> { where(kind: LOST) }
  scope :found,      -> { where(kind: FOUND) }
  scope :adoption,   -> { where(kind: ADOPTION) }
  scope :mate,       -> { where(kind: MATE) }

  mount_uploader :photo, ImageUploader

  def photo
    if pet
      pet.photo
    else
      super
    end
  end

  def name
    if pet
      pet.name
    else
      super
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_pet, only: [:new, :create]
  before_action :set_post_kind
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if (params["k"] == Post::LOST)
      @title = "Extraviadas"
      @type = Post::LOST
      @posts = Post.lost
    elsif (params["k"] == Post::FOUND)
      @title = "Encontradas"
      @type = Post::FOUND
      @posts = Post.found
    elsif (params["k"] == Post::ADOPTION)
      @title = "en Adopción"
      @type = Post::ADOPTION
      @posts = Post.adoption
    elsif (params["k"] == Post::MATE)
      @title = "buscando Pareja"
      @type = Post::MATE
      @posts = Post.mate
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/select
  def select
    @user = current_user
    @pets = @user.pets
  end

  # GET /posts/new
  def new
    if @pet
      @post = @pet.posts.new
    else
      @post = Post.new
    end

    @user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    if @pet
      @post = @pet.posts.new post_params
    else
      @post = Post.new post_params
    end
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Tu anuncio se ha creado con éxito.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Tu anuncio se ha editado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_pet
      @pet = Pet.find(params[:pet_id]) unless params[:pet_id].blank?
    end

    def set_post_kind
      kind = params[:k] || @post.try(:kind)

      if kind == Post::LOST
        @title = "Extraviadas"
        @type  = Post::LOST
      elsif kind == Post::FOUND
        @title = "Encontradas"
        @type  = Post::FOUND
      elsif kind == Post::ADOPTION
        @title = "en Adopción"
        @type  = Post::ADOPTION
      elsif kind == Post::MATE
        @title = "buscando Pareja"
        @type  = Post::MATE
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :kind, :photo, :name, :address)
    end
end

app/views/posts/_form.html.erb
<div class='row' >
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
<%= form_for [@pet, @post], html: {multipart: true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="center">
    <%= image_tag @post.photo.to_s, style: "max-width: 150px", class: 'frame-img' %>

    <% unless @post.pet %>
      <div class="field">
        <%= f.file_field :photo %>
      </div>
    <% end %>
  </div>

  <% unless @post.pet %>
    <div class="form-group">
      <label class="control-label">Direcci&oacute;n: </label>
      <%= f.text_field :address, class:'form-control' %>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label">Mensaje: </label>
    <%= f.text_area :description, class:'form-control' %>
  </div>

  <% if @type %>
    <%= f.hidden_field :kind, value: @type %>
  <% else %>
    <div class="form-group">
      <label class="control-label">Tipo: </label>
      <%= f.select :kind, post_kinds_for_select, class:'form-control' %>
    </div>
  <% end %>

  <div class="center">
    <button type="submit" class="pet-button">
      <%= image_tag("check-72px.png", :alt => "Enviar") %>
    </button>
   </div>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<h2>EDITAR ANUNCIO</h2>
<div class='divisor'></div>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Mascotas
<%= @title %>
</h1>

<div class="divisor">
  <%= image_for_post_kind(@type) %>
</div>

<div class="row post">
  <% if @posts.blank? %>
    <div class="no-content">
      No hay anuncios creados. Crea un nuevo anuncio presionando el botón +
    </div>
  <% end %>
  <% @posts.each do |post| %>
    <div class="col-xs-6 col-sm-4 col-md-3 polaroid">
      <%= link_to post_path(post), { style: "background-image: url('#{image_path post.photo}');" } do %>
        <span class="image-caption"><%= post.name %></span>
      <% end %>
    </div>
  <% end %>
</div>

<div class="add-button">
  <%= link_to (image_tag("plus-72px.png", :alt => "Anuncio Nuevo")), select_posts_path(k: params[:k]) %>
</div>

app/views/posts/new.html.erb
<h1>Mascotas
<%= @title %>
</h1>

<h3>AGREGAR ANUNCIO</h3>

<div class="divisor">
  <%= image_for_post_kind(@type) %>
</div>

<%= render 'form' %>

app/views/posts/select.html.erb
<h1>Mascotas
<%= @title %>
</h1>

<h3>SELECCIONAR MASCOTA</h3>

<div class="divisor">
  <%= image_for_post_kind(@type) %>
</div>

<div class="row post">
  <% @pets.each do |pet| %>
    <div class="col-xs-6 col-sm-4 col-md-3 polaroid">
      <%= link_to new_pet_post_path(pet, k: params[:k]), { style: "background-image: url('#{image_path pet.photo}');" } do %>
        <span class="image-caption"><%= pet.name %></span>
      <% end %>
    </div>
  <% end %>
</div>

<h3>Crear un post para una mascota que no te pertenece presionando el botón +</h3>

<div class="add-button">
  <%= link_to (image_tag("plus-72px.png", :alt => "Anuncio Nuevo")), new_post_path(k: params[:k]) %>
</div>

app/views/posts/show.html.erb
<h1>Mascotas
<%= @title %>
</h1>

<div class="divisor">
  <%= image_for_post_kind(@type) %>
</div>

<div class='row' >
 <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
  <div class="media">
    <div class="pull-left">
      <%= image_tag @post.photo, style: "max-width: 150px",  class: 'frame-img' %>
    </div>
    <div class="media-body">
      <h3 class="media-heading"><%=@post.name%></h3>
      <p>Dirección: <%= @post.address %></p>
      <p>Tipo: <%=t "post.kind.#{@post.kind}" %></p>
    </div>
  </div>

  <div class="panel panel-default" style='margin-top:5px;'>
    <div class="panel-heading">Mensaje</div>
    <div class="panel-body">
      <p><%= @post.description %></p>
    </div>
  </div>

  <div class="panel panel-default" style='margin-top:5px;'>
    <div class="panel-heading">Datos de contacto</div>
    <div class="panel-body">
      <p>Nombre: <%= @post.user.full_name %></p>
      <p>Email: <%= @post.user.email %></p>
      <p>N&uacute;mero telef&oacute;nico: <%= @post.user.phone_number %></p>
      <p>Ubicaci&oacute;n: <%= @post.user.location %></p>
    </div>
  </div>

  <% if @post.pet %>
    <p>
      <%= link_to 'Ver mascota', @post.pet, class: 'btn btn-success' %>
    </p>
  <% end %>

  <div class="social-buttons">
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= post_url(@post) %>" data-via="MiMascotaNet" data-lang="en">Tweet</a>
    <g:plusone size="medium"></g:plusone>
    <div class="fb-like" data-href="<%= post_url(@post) %>" data-width="100" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
  </div>

  <% if current_user == @post.user %>
    <div class="add-button">
      <%= link_to (image_tag("edit-72px.png", :alt => "Editar")), edit_post_path(@post) %>
    </div>
  <% end %>

  <div class="panel panel-default" style='margin-top: 5px; padding-top: 15px;'>
    <div style="text-align: center;">
      <div class="fb-comments" data-href="<%= post_url(@post) %>" data-numposts="5" data-colorscheme="light"></div>
    </div>
  </div>
 </div>
</div>